import Head from 'next/head'
import Calculator from './Calculator';


export default function Home() {
  return (
    <div >
      <Head>
        <title>Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon2.ico" />
      </Head>
      <Calculator></Calculator>
    </div>
  )
}
